apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keystone
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://tarballs.opendev.org/openstack/openstack-helm'
    chart: keystone
    targetRevision: 2024.2.4
    helm:
      parameters:
        # --- CRITICAL: Job Flags (Boolean without quotes sometimes matters in older charts) ---
        - name: manifests.job_db_init
          value: "true"
        - name: manifests.job_db_sync
          value: "true"
        - name: manifests.job_bootstrap
          value: "true"
        - name: manifests.job_credential_setup
          value: "true"
        - name: manifests.job_fernet_setup
          value: "true"
        
        # --- Image Repo Overrides (To prevent rate limits here too) ---
        # OpenStack-Helm usually uses quay.io or docker.io. Let's be safe.
        # We will stick to defaults for now unless we see ErrImagePull.

        # --- Connectivity ---
        - name: conf.keystone.database.connection
          value: mysql+pymysql://keystone:password@mariadb.openstack.svc.cluster.local/keystone
        - name: conf.keystone.oslo_messaging_rabbit.transport_url
          value: rabbit://openstack:password@rabbitmq.openstack.svc.cluster.local:5672/
        - name: conf.keystone.cache.backend
          value: dogpile.cache.memcached
        - name: conf.keystone.cache.memcache_servers
          value: memcached.openstack.svc.cluster.local:11211
        - name: conf.keystone.DEFAULT.admin_token
          value: password

        # --- Resource Limits (VERY IMPORTANT) ---
        - name: pod.replicas.api
          value: "1"
        # Force low resources for ALL jobs and pods
        - name: pod.resources.api.requests.memory
          value: "256Mi"
        - name: pod.resources.api.requests.cpu
          value: "50m"
        - name: pod.resources.jobs.db_init.requests.memory
          value: "256Mi"
        - name: pod.resources.jobs.db_init.requests.cpu
          value: "50m"
        - name: pod.resources.jobs.db_sync.requests.memory
          value: "256Mi"
        - name: pod.resources.jobs.db_sync.requests.cpu
          value: "50m"
        - name: pod.resources.jobs.bootstrap.requests.memory
          value: "256Mi"
        - name: pod.resources.jobs.bootstrap.requests.cpu
          value: "50m"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
