apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memcached
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 6.5.5
    chart: memcached
    helm:
      parameters:
        - name: architecture
          value: standalone
        - name: auth.enabled
          value: "false" # Keep it simple for internal network
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
