apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memcached
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 7.0.0 # <--- MAJOR UPGRADE (was 6.5.5)
    chart: memcached
    helm:
      parameters:
        # Remove the 'image.tag' override.
        - name: architecture
          value: standalone
        - name: auth.enabled
          value: "false"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
