apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memcached
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 7.0.0
    chart: memcached
    helm:
      parameters:
        # --- MAKE SURE INDENTATION MATCHES EXACTLY ---
        - name: image.tag
          value: "1.6-debian-12"
        - name: architecture
          value: standalone
        - name: auth.enabled
          value: "false"
        # ---------------------------------------------
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
