apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    targetRevision: 14.6.6
    helm:
      releaseName: rabbitmq
      values: |
        replicaCount: 1
        auth:
          password: password
          erlangCookie: changemeplease
        tls:
          enabled: true
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
        communityPlugins: "https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/3.8.9/rabbitmq_delayed_message_exchange-3.8.9-0199d11c.ez"
        extraPlugins: "rabbitmq_delayed_message_exchange"
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true   
