apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 15.0.0
    chart: rabbitmq
    helm:
      parameters:
        # ------------------------------------------------
        # 1. MAIN IMAGE CONFIG (Use AWS Mirror)
        # ------------------------------------------------
        - name: image.registry
          value: "public.ecr.aws"
        - name: image.repository
          value: "bitnami/rabbitmq"
        - name: image.tag
          value: "latest"
        - name: image.pullPolicy
          value: "Always"

        # ------------------------------------------------
        # 2. INIT CONTAINER CONFIG (Use AWS Mirror)
        # This is likely the part that was failing before.
        # ------------------------------------------------
        - name: volumePermissions.enabled
          value: "true"
        - name: volumePermissions.image.registry
          value: "public.ecr.aws"
        - name: volumePermissions.image.repository
          value: "bitnami/os-shell"
        - name: volumePermissions.image.tag
          value: "latest"
        - name: volumePermissions.image.pullPolicy
          value: "Always"

        # ------------------------------------------------
        # 3. APPLICATION CONFIG
        # ------------------------------------------------
        - name: persistence.storageClass
          value: general
        - name: persistence.size
          value: 5Gi
        - name: auth.username
          value: openstack
        - name: auth.password
          value: password
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
